name = "sepay-payment-gateway"
main = "src/index.js"
compatibility_date = "2024-01-01"
account_id = "d4a30462b305677d4a98c834d8e5f06c"

# KV namespace for payment status storage
[[kv_namespaces]]
binding = "PAYMENT_STATUS"
id = "c7c7142e2a1d4eaca7ecaabdaceed881"
